import { writable } from 'svelte/store'

const scenes = 
    [{
        name: 'Movie Start',
        key: 0,
        start: 0,
        end: 19,
        location:'None',
        search: 'None',
        coordinates: 'None',
        info: '<strong>From Wikipedia</strong>: Samsara is a 2011 American non-narrative documentary film of international imagery directed by Ron Fricke and produced by Mark Magidson, who also collaborated on Baraka (1992), a film of a similar vein, and Chronos (1985).',
    },
    {
        name: 'Balinese Tari Legong Dancers',
        key: 1,
        start: 20,
        end: 109,
        location: 'Bali, Indonesia',
        search: 'Tri+Pusaka+Sakti+Arts+Foundation',
        coordinates: '-8.584905,115.276968&zoom=4',
        info: '<a href="https://pusakasaktiarts.com/" target="_blank">Tri Pusaka Sakti Art Foundation</a><br><a href="https://en.wikipedia.org/wiki/Legong" target="_blank">From Wikipedia: </a>Lelong is a form of Balinese dance. It is a refined dance form characterized by intricate finger movements, complicated footwork, and expressive gestures and facial expressions.',
    },
    {
        name: 'Kilauea Volcano',
        key: 2,
        start: 110,
        end: 213,
        location:'Hawai\'i, Hawaii',
        search: 'Kīlauea+Volcano',
        coordinates: '19.406280,-155.283678&zoom=6',
        info: 'None',
    },
    {
        name: 'Preserved Baby/Fetus (Pending)',
        key: 3,
        start: 214,
        end: 245,
        location:'None',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Tollund Man',
        key: 4,
        start: 246,
        end: 261,
        location:'Silkeborg, Denmark',
        search: 'Silkeborg+Museum+Hovedgården',
        coordinates: '56.169070,9.552999&zoom=5',
        info: 'Silkeborg Museum, Hovedgården',
    },
    {
        name: 'Mask of Tutankhamun',
        key: 5,
        start: 262,
        end: 290,
        location:'Cairo, Egypt',
        search: 'Museum+of+Egyptian+Antiquities&zoom=5',
        coordinates: '30.048297,31.233638',
        info: 'The Museum of Egyptian Antiquities',
    },
    {
        name: 'Title Drop - SAMSARA',
        key: 6,
        start: 291,
        end: 314,
        location:'None',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Taung Kalat Monastery',
        key: 7,
        start: 315,
        end: 350,
        location:'Mount Popa, Myanmar',
        search: 'Taung+Kalat+Monastery',
        coordinates: '20.912974,95.208672&zoom=6',
        info: 'None',
    },
    {
        name: 'Bagan Archaeological Zone',
        key: 8,
        start: 351,
        end: 476,
        location:'Old Bagan, Mandalay Region, Myanmar',
        search: 'Bagan+Archaeological+Zone',
        coordinates: '21.168226,94.856173&zoom=6',
        info: 'None',
    },
    {
        name: 'Statue of Maitreya Buddha',
        key: 9,
        start: 477,
        end: 498,
        location:'Thiksey, Ladakh Territory, India',
        search: 'Thiksey+Monastery',
        coordinates: '34.056964,77.666946&zoom=5',
        info: 'Thiksey Monastery',
    },
    {
        name: 'Thiksey Monastery',
        key: 10,
        start: 499,
        end: 555,
        location:'Thiksey, Ladakh Territory, India',
        search: 'Thiksey+Monastery',
        coordinates: '34.056964,77.666946&zoom=6',
        info: 'None',
    },
    {
        name: 'Je Tsongkhapa/Prayer Wheel',
        key: 11,
        start: 556,
        end: 585,
        location:'Thiksey, Ladakh Territory, India',
        search: 'Thiksey+Monastery',
        coordinates: '34.056964,77.666946&zoom=7',
        info: 'Thiksey Monastery',
    },
    {
        name: 'Tibetan Sand Mandala',
        key: 12,
        start: 586,
        end: 730,
        location:'Thiksey, Ladakh Territory, India',
        search: 'Thiksey+Monastery',
        coordinates: '34.056964,77.666946&zoom=8',
        info: 'Thiksey Monastery',
    },
    {
        name: '1000 Hands Dance',
        key: 13,
        start: 731,
        end: 753,
        location:'Beijing, China',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Desert (Pending)',
        key: 14,
        start: 754,
        end: 787,
        location:'None',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Mt. Nemrut National Park',
        key: 15,
        start: 788,
        end: 861,
        location:'Adiyaman, Turkey',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Petra, Jordan',
        key: 16,
        start: 862,
        end: 909,
        location:'Petra, Jordan',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Goreme Open Air Museum',
        key: 17,
        start: 910,
        end: 932,
        location:'Cappadocia, Turkey',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Bandiagara Escarpment',
        key: 18,
        start: 933,
        end: 965,
        location:'Dogon Village, Mali',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Kolmanskop, Namibia',
        key: 19,
        start: 966,
        end: 1050,
        location:'Kolmanskop, Namibia',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Ninth Ward, New Orleans',
        key: 20,
        start: 1051,
        end: 1171,
        location:'New Orleans, Louisiana, USA',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'The Hall of Mirrors',
        key: 21,
        start: 1172,
        end: 1218,
        location:'Versailles, France',
        search: 'None',
        coordinates: 'None',
        info: 'Palace of Versailles',
    },
    {
        name: 'Painting (Pending)',
        key: 22,
        start: 1219,
        end: 1250,
        location:'Versailles, France',
        search: 'None',
        coordinates: 'None',
        info: 'Palace of Versailles',
    },
    {
        name: 'Divino Salvador Church',
        key: 23,
        start: 1251,
        end: 1303,
        location:'São Paulo, Brazil',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Reims Cathedral',
        key: 24,
        start: 1304,
        end: 1336,
        location:'Reims, France',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Notre Dame Cathedral',
        key: 25,
        start: 1337,
        end: 1352,
        location:'Paris, France',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Statues (Pending)',
        key: 26,
        start: 1353,
        end: 1381,
        location:'Paris, France',
        search: 'None',
        coordinates: 'None',
        info: 'Notre Dame Cathedral',
    },
    {
        name: 'Rosalia Lombardo',
        key: 27,
        start: 1382,
        end: 1409,
        location:'Palermo, Sicily, Italy',
        search: 'None',
        coordinates: 'None',
        info: 'Capuchin Catacombs of Palermo',
    },
    {
        name: 'Sainte-Chapelle',
        key: 28,
        start: 1410,
        end: 1430,
        location:'Paris, France',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Mont-Saint-Michel',
        key: 29,
        start: 1431,
        end: 1456,
        location:'Normandy, France',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Namib-Naukluft National Park',
        key: 30,
        start: 1457,
        end: 1511,
        location:'Sossusvlei, Namibia',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Ancient Bristlecone Pine Forest',
        key: 31,
        start: 1512,
        end: 1528,
        location:'Bishop, California, USA',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Unnamed Mountain',
        key: 32,
        start: 1529,
        end: 1560,
        location:'None',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Mont Blanc',
        key: 33,
        start: 1561,
        end: 1633,
        location:'Alps, Europe',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Mono Basin National Scenic Area',
        key: 34,
        start: 1634,
        end: 1688,
        location:'Mono Lake, California, USA',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Arches National Park',
        key: 35,
        start: 1689,
        end: 1717,
        location:'Utah, USA',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Hunt\'s Mesa, Monument Valley',
        key: 36,
        start: 1718,
        end: 1729,
        location:'Arizona, USA',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Antelope Canyon',
        key: 37,
        start: 1730,
        end: 1783,
        location:'Arizona, USA',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Epupa Falls',
        key: 38,
        start: 1784,
        end: 1832,
        location:'Epupa, Namibia',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Mursi Village',
        key: 39,
        start: 1833,
        end: 1900,
        location:'Omo Valley, Ethiopia',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Himba Village',
        key: 40,
        start: 1901,
        end: 2019,
        location:'Kunene, Namibia',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Los Angeles Highways (Pending)',
        key: 41,
        start: 2020,
        end: 2049,
        location:'California, USA',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Tattooed Dad',
        key: 42,
        start: 2050,
        end: 2092,
        location:'USA',
        search: 'None',
        coordinates: 'None',
        info: 'Marcos Luna',
    },
    {
        name: 'Los Angeles Skyline',
        key: 43,
        start: 2093,
        end: 2141,
        location:'California, USA',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: '(Pending) Highway',
        key: 44,
        start: 2142,
        end: 2160,
        location:'None',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: '(Pending) Skyline',
        key: 45,
        start: 2161,
        end: 2178,
        location:'None',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Hiroshi Ishiguro Robot Clone',
        key: 46,
        start: 2179,
        end: 2216,
        location:'Osaka University, Suita, Japan',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Office (Pending)',
        key: 47,
        start: 2217,
        end: 2236,
        location:'None',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Female Robot',
        key: 48,
        start: 2237,
        end: 2244,
        location:'Osaka University, Suita, Japan',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Oliver De Sagazan Performance',
        key: 49,
        start: 2245,
        end: 2387,
        location:'Paris, France',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Female Robot Pt.2',
        key: 50,
        start: 2388,
        end: 2395,
        location:'Osaka University, Suita, Japan',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: '(Pending) Highway/Bridge',
        key: 51,
        start: 2396,
        end: 2402,
        location:'None',
        search: 'None',
        coordinates: 'None',
        info: 'Shanghai(?)',
    },
    {
        name: 'Toshimaen/Hydropolis',
        key: 52,
        start: 2403,
        end: 2409,
        location:'Tokyo, Japan',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Lotte Kasai Golf',
        key: 53,
        start: 2410,
        end: 2424,
        location:'Chiba, Japan',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'YMCA Los Angeles (Pending)',
        key: 54,
        start: 2425,
        end: 2433,
        location:'California, USA',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Ski Dubai',
        key: 55,
        start: 2434,
        end: 2466,
        location:'Dubai, United Arab Emirates',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Mosque/Burj Al Arab Hotel',
        key: 56,
        start: 2467,
        end: 2478,
        location:'Dubai, United Arab Emirates',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Dubai Skyline/Burj Khalifa',
        key: 57,
        start: 2479,
        end: 2498,
        location:'Dubai, United Arab Emirates',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'The World Islands',
        key: 58,
        start: 2499,
        end: 2532,
        location:'Dubai, United Arab Emirates',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Palm Island Development',
        key: 59,
        start: 2533,
        end: 2572,
        location:'Dubai, United Arab Emirates',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Burj Al Arab Hotel',
        key: 60,
        start: 2573,
        end: 2598,
        location:'Dubai, United Arab Emirates',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'The Waterfall - Dubai Mall',
        key: 61,
        start: 2599,
        end: 2617,
        location:'Dubai, United Arab Emirates',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Dubai Skyline/Burj Khalifa Pt.2',
        key: 62,
        start: 2618,
        end: 2660,
        location:'Dubai, United Arab Emirates',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Niqab - Dubai Mall',
        key: 63,
        start: 2661,
        end: 2675,
        location:'Dubai, United Arab Emirates',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Galleria Vittorio Emanuele II',
        key: 64,
        start: 2676,
        end: 2684,
        location:'Milan, Italy',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Teatro alla Scala',
        key: 65,
        start: 2685,
        end: 2720,
        location:'Milan, Italy',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shibuya Crossing',
        key: 66,
        start: 2721,
        end: 2727,
        location:'Tokyo, Japan',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Tokyo Metro (Pending)',
        key: 67,
        start: 2728,
        end: 2751,
        location:'Tokyo, Japan',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Yoyogi Park/Metro',
        key: 68,
        start: 2752,
        end: 2784,
        location: 'Tokyo, Japan',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'São Paulo Metro',
        key: 69,
        start: 2785,
        end: 2803,
        location: 'São Paulo, Brazil',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Tattooed Couple (Pending)',
        key: 70,
        start: 2804,
        end: 2815,
        location: 'None',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'São Paulo Metro Pt.2',
        key: 71,
        start: 2816,
        end: 2823,
        location: 'São Paulo, Brazil',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Factory City China',
        key: 72,
        start: 2824,
        end: 2924,
        location: 'Zhangzhou, Fujian, China',
        search: '24.495000+117.939000',
        coordinates: '24.495000,117.939000&zoom=6',
        info: 'None',
    }
]

export let seconds = writable(0)
export let storedcurrent = writable(scenes[0])
export let storedscenes = writable(scenes)

export function formatTime(n){
    const h = Math.floor(n / 3600).toString().padStart(2,'0'),
    m = Math.floor(n % 3600 / 60).toString().padStart(2,'0'),
    s = Math.floor(n % 60).toString().padStart(2,'0')

    return h + ':' + m + ':' + s
}