import { writable } from 'svelte/store'

const scenes = 
    [{
        name: 'Movie Start',
        key: 0,
        start: 0,
        end: 19,
        location:'None',
        search: 'None',
        coordinates: 'None',
        info: '<strong>From Wikipedia</strong>: Samsara is a 2011 American non-narrative documentary film of international imagery directed by Ron Fricke and produced by Mark Magidson, who also collaborated on Baraka (1992), a film of a similar vein, and Chronos (1985).',
    },
    {
        name: 'Balinese Tari Legong Dancers',
        key: 1,
        start: 20,
        end: 109,
        location: 'Bali, Indonesia',
        search: 'Tri+Pusaka+Sakti+Arts+Foundation',
        coordinates: '-8.584905,115.276968&zoom=4',
        info: '<a href="https://pusakasaktiarts.com/" target="_blank">Tri Pusaka Sakti Art Foundation</a><br><a href="https://en.wikipedia.org/wiki/Legong" target="_blank">From Wikipedia: </a>Lelong is a form of Balinese dance. It is a refined dance form characterized by intricate finger movements, complicated footwork, and expressive gestures and facial expressions.',
    },
    {
        name: 'Kilauea Volcano',
        key: 2,
        start: 110,
        end: 213,
        location:'Hawai\'i, Hawaii',
        search: 'Kīlauea+Volcano',
        coordinates: '19.406280,-155.283678&zoom=6',
        info: 'None',
    },
    {
        name: 'Unnamed Preserved Fetus',
        key: 3,
        start: 214,
        end: 245,
        location:'None',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Tollund Man',
        key: 4,
        start: 246,
        end: 261,
        location:'Silkeborg, Denmark',
        search: 'Silkeborg+Museum+Hovedgården',
        coordinates: '56.169070,9.552999&zoom=5',
        info: 'Silkeborg Museum, Hovedgården',
    },
    {
        name: 'Mask of Tutankhamun',
        key: 5,
        start: 262,
        end: 290,
        location:'Cairo, Egypt',
        search: 'Museum+of+Egyptian+Antiquities&zoom=5',
        coordinates: '30.048297,31.233638',
        info: 'The Museum of Egyptian Antiquities',
    },
    {
        name: 'Title Drop',
        key: 6,
        start: 291,
        end: 314,
        location:'None',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Taung Kalat Monastery',
        key: 7,
        start: 315,
        end: 350,
        location:'Mount Popa, Myanmar',
        search: 'Taung+Kalat+Monastery',
        coordinates: '20.912974,95.208672&zoom=6',
        info: 'None',
    },
    {
        name: 'Bagan Archaeological Zone',
        key: 8,
        start: 351,
        end: 476,
        location:'Old Bagan, Mandalay Region, Myanmar',
        search: 'Bagan+Archaeological+Zone',
        coordinates: '21.168226,94.856173&zoom=6',
        info: 'None',
    },
    {
        name: 'Statue of Maitreya Buddha - Thiksey Monastery',
        key: 9,
        start: 477,
        end: 498,
        location:'Thiksey, Ladakh Territory, India',
        search: 'Thiksey+Monastery',
        coordinates: '34.056964,77.666946&zoom=5',
        info: 'Thiksey Monastery',
    },
    {
        name: 'Thiksey Monastery',
        key: 10,
        start: 499,
        end: 555,
        location:'Thiksey, Ladakh Territory, India',
        search: 'Thiksey+Monastery',
        coordinates: '34.056964,77.666946&zoom=6',
        info: 'None',
    },
    {
        name: 'Je Tsongkhapa/Prayer Wheel - Thiksey Monastery',
        key: 11,
        start: 556,
        end: 585,
        location:'Thiksey, Ladakh Territory, India',
        search: 'Thiksey+Monastery',
        coordinates: '34.056964,77.666946&zoom=7',
        info: 'Thiksey Monastery',
    },
    {
        name: 'Sand mandala - Thiksey Monastery',
        key: 12,
        start: 586,
        end: 730,
        location:'Thiksey, Ladakh Territory, India',
        search: 'Thiksey+Monastery',
        coordinates: '34.056964,77.666946&zoom=8',
        info: 'Thiksey Monastery',
    },
    {
        name: 'Shot13 - Beijing (1000 HANDS DANCE)',
        key: 13,
        start: 731,
        end: 753,
        location:'Beijing, China',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot14 - Desert',
        key: 14,
        start: 732,
        end: 787,
        location:'None',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot15 - Mt. Nemrut National Park',
        key: 15,
        start: 788,
        end: 861,
        location:'Adiyaman, Turkey',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot16 - Petra, Jordan',
        key: 16,
        start: 862,
        end: 909,
        location:'Petra, Jordan',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot17 - Goreme Open Air Museum',
        key: 17,
        start: 910,
        end: 932,
        location:'Cappadocia, Turkey',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot18 - Bandiagara Escarpment',
        key: 18,
        start: 933,
        end: 965,
        location:'Dogon Village, Mali',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot19 - Kolmanskop, Namibia',
        key: 19,
        start: 966,
        end: 1050,
        location:'Kolmanskop, Namibia',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot20 - Ninth Ward, New Orleans',
        key: 20,
        start: 1051,
        end: 1171,
        location:'New Orleans, Louisiana, USA',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot21 - The Hall of Mirrors, Palace of Versailles',
        key: 21,
        start: 1172,
        end: 1218,
        location:'Versailles, France',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot22 - Painting (Pending), Palace of Versailles',
        key: 22,
        start: 1219,
        end: 1250,
        location:'Versailles, France',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot23 - Divino Salvador Church',
        key: 23,
        start: 1251,
        end: 1303,
        location:'São Paulo, Brazil',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot24 - Reims Cathedral',
        key: 24,
        start: 1304,
        end: 1336,
        location:'Reims, France',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot25 - Notre Dame Cathedral',
        key: 25,
        start: 1337,
        end: 1352,
        location:'Paris, France',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot26 - Statues (Pending), Notre Dame Cathedral',
        key: 26,
        start: 1353,
        end: 1381,
        location:'Paris, France',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot27 - Rosalia Lombardo',
        key: 27,
        start: 1382,
        end: 1409,
        location:'Palermo, Sicily, Italy',
        search: 'None',
        coordinates: 'None',
        info: 'Capuchin Catacombs of Palermo',
    },
    {
        name: 'Shot28 - Sainte-Chapelle',
        key: 28,
        start: 1410,
        end: 1430,
        location:'Paris, France',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot29 - Mont-Saint-Michel',
        key: 29,
        start: 1431,
        end: 1456,
        location:'Normandy, France',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot30 - Namib-Naukluft National Park',
        key: 30,
        start: 1457,
        end: 1511,
        location:'Sossusvlei, Namibia',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot31 - Ancient Bristlecone Pine Forest',
        key: 31,
        start: 1512,
        end: 1528,
        location:'Bishop, California, USA',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot32 - Unnamed Mountain',
        key: 32,
        start: 1529,
        end: 1560,
        location:'None',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot33 - Mont Blanc',
        key: 33,
        start: 1561,
        end: 1633,
        location:'Alps, Europe',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot34 - Mono Basin National Scenic Area',
        key: 34,
        start: 1634,
        end: 1688,
        location:'Mono Lake, California, USA',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot35 - Arches National Park',
        key: 35,
        start: 1689,
        end: 1717,
        location:'Utah, USA',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot36 - Monument Valley',
        key: 36,
        start: 1718,
        end: 1729,
        location:'Arizona, USA',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot37 - Antelope Canyon',
        key: 37,
        start: 1730,
        end: 1783,
        location:'Arizona, USA',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot38 - Epupa Falls',
        key: 38,
        start: 1784,
        end: 1832,
        location:'Epupa, Namibia',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot39 - Mursi people',
        key: 39,
        start: 1833,
        end: 1900,
        location:'Omo Valley, Ethiopia',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot40 - Himba people',
        key: 40,
        start: 1901,
        end: 2019,
        location:'Kunene Region, Namibia',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot41 - Unnamed Highways',
        key: 41,
        start: 2020,
        end: 2049,
        location:'USA',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
    {
        name: 'Shot42',
        key: 42,
        start: 2050,
        end: 2049,
        location:'USA',
        search: 'None',
        coordinates: 'None',
        info: 'None',
    },
]

export let seconds = writable(0)
export let storedcurrent = writable(scenes[0])
export let storedscenes = writable(scenes)

export function formatTime(n){
    const h = Math.floor(n / 3600).toString().padStart(2,'0'),
    m = Math.floor(n % 3600 / 60).toString().padStart(2,'0'),
    s = Math.floor(n % 60).toString().padStart(2,'0')

    return h + ':' + m + ':' + s
}